name: ""
on:
  pull_request:
    types: [opened]
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: CultureHQ/actions-yarn@master
        with:
          args: install

      - name: Run action
        uses: ./internal/actions/test
